services:
  ygl-server:
    build: .
    ports:
      - 8083:8083
    volumes:
      - ./data:/app/data
    develop:
      watch:
        - action: rebuild
          path: ./ygl-server.go
    env_file: .env
