brokers:
  - name: Leigha
    url: "https://ygl.is/leigha-emery-1"
  - name: Denis
    url: "https://ygl.is/99334"

notifications:
  - "tgram://<your-bot-token>/<your-channel-id>"
  - "ntfys://ntfy.sh/some-channel"

filter:
  bedsMin: 2
  bedsMax: 2
  priceMax: 3200
